apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
  labels:
    app.kubernetes.io/name: cloudflared
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/component: tunnel
  endpoints:
    - port: metrics
      path: /metrics
      interval: 60s
