apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-tridata-public-oidc
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: authentik-tridata-public-oidc
  data:
    - secretKey: AUTHENTIK_TRIDATA_PUBLIC_CLIENT_SECRET
      remoteRef: {key: tridata/public/oidc, property: client_secret}
