apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-tridata-oidc
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: authentik-tridata-oidc
  data:
    - secretKey: AUTHENTIK_BOOTSTRAP_TRIDATA_CLIENT_ID
      remoteRef: {key: tridata/oidc, property: client_id}
    - secretKey: AUTHENTIK_BOOTSTRAP_TRIDATA_CLIENT_SECRET
      remoteRef: {key: tridata/oidc, property: client_secret}
    - secretKey: AUTHENTIK_BOOTSTRAP_TRIDATA_OWNER
      remoteRef: {key: tridata/staging/runtime, property: owner_username}
