apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-tridata-google
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: authentik-tridata-google
  data:
    - secretKey: AUTHENTIK_TRIDATA_GOOGLE_CLIENT_ID
      remoteRef: {key: tridata/public/google, property: client_id}
    - secretKey: AUTHENTIK_TRIDATA_GOOGLE_CLIENT_SECRET
      remoteRef: {key: tridata/public/google, property: client_secret}
