apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: authentik
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: authentik
      app.kubernetes.io/component: server
  endpoints:
    - port: metrics
      path: /metrics
      interval: 60s
