apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: woodpecker-server
  namespace: woodpecker
  labels:
    app.kubernetes.io/name: woodpecker
    app.kubernetes.io/component: server
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: woodpecker
      app.kubernetes.io/component: server
  endpoints:
    - port: http
      path: /metrics
      interval: 60s
